### ISSUE TITLE
감정그래프 초기 UI 작업

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/narang#19]
[chart.js + react 참고 사이트](https://velog.io/@treejy/React%EC%97%90%EC%84%9C-Chart.js-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-with-TypeScript)

**Comment by kkn1125** [comment]
![image](https://user-images.githubusercontent.com/71887242/180637806-6d6c90af-dbab-4401-964a-91e671e3051e.png)

**Comment by ohoraming** [comment]
# react-chartjs-2 관련 자료
- [GITHUB](https://github.com/reactchartjs/react-chartjs-2)
- [공식 사이트](https://react-chartjs-2.js.org/)

**Comment by kkn1125** [comment]
# 그래프 호버 툴팁 설정

[tooltip 설정](https://minaminaworld.tistory.com/182) 참고
