### ISSUE TITLE
[FE] 추천페이지 UI 작업

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/narang#31]
# 추천페이지 더미 데이터

[sample api 소개](https://blog.logrocket.com/deep-dive-react-native-flatlist/) 블로그 참고
[sample api](https://sampleapis.com/) 참고

**Comment by ohoraming** [comment]
- [coffee api](https://api.sampleapis.com/coffee/hot) 로 추천 아이템 생성
- 추천 활동/책 구절 등 추가 필요

**Comment by kkn1125** [comment]
추천 활동 및 책 구절 추가는 다음 이슈로
