### ISSUE TITLE
[FE] About page UI 작업

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/narang#36]
#1 초기안 이슈에 링크 참조한 예시를 토대로 작성

**Comment by ohoraming** [comment]
의견!
- [mui의 About](https://mui.com/about/) 디자인 참고 하는 건 어떤지
- 항목은: 애플리케이션 구상 동기, 목적, 팀원

**Comment by kkn1125** [comment]
확인!

- 1,2,3 섹션 참고해서 추후 백엔드 완료 시 about 수정 예정
- 수정 반영 후 해당 이슈를 닫는 것으로 하겠음!
