### ISSUE TITLE
[BE] 백엔드 계획 의논

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/narang#41]
# 백엔드 DB + API 설계

각 클래스 공통 필드명

- id
- regdate
- updates
- _class

## DB

- [x] User
  - nickname
  - email
  - password
  - profileImg
  - phone
  - isFaceSign
- [x] FaceImage
  - uid
  - imgPath
- [x] Diary
  - uid (추가)
  - title
  - content
  - author
  - isShare
- [x] Emotion
  - uid (추가)
  - did (추가)
  - advice
  - comparative
  - emoji
  - negative: Whether
  - normal: Normal
  - positive: Whether
  - score
    - [x] Whether (추가)
      - score
      - count
      - words
    - [x] Normal (추가)
      - count
- [x] Comment
  - did (추가)
  - content
  - author
  - mention
- [x] Product (변경)
  - category
  - pid
  - name
  - price
  - amount
  - content
  - seller
  - isSoldOut
  - regdate
  - updates
- [x] Cart
  - cid: 계속 변경 hash
  - uid
  - pid
  - amount
  - isOrdered
  - regdate
  - updates
- [x] Bill
  - bid
  - pid
  - uid
  - amount
  - price
  - regdate
- [x] Like
  - uid
  - did
  - isLike

**Comment by kkn1125** [comment]
# 백엔드 DB + API 설계

## API

- [x] User
  - `GET` `/api/users` : 사용자 전체 목록 조회
  - `GET` `/api/user/:uid` : 사용자 단건 조회
  - `GET` `/api/user/nickname/:nickName` : 사용자 단건 조회 (추가)
  - `GET` `/api/user/email/:email` : 사용자 단건 조회 (추가)
  - `POST` `/api/face/signin` : 사용자 로그인 (안면인식 로그인) (추가)
  - `POST` `/api/signin` : 사용자 로그인 (일반 로그인) (추가)
  - `POST` `/token/confirm` : 토큰 확인 (추가)
  - `POST` `/user/signout` : 사용자 로그아웃 (추가)
  - `POST` `/user/checkPassword` : 비밀번호 확인 (추가)
  - `POST` `/fileupload` : 얼굴 이미지 업로드 (추가)
  - `POST` `/api/user` : 사용자 등록 (회원가입)
  - `PUT` `/api/user` : 사용자 정보 수정 (회원정보 수정)
  - `DELETE` `/api/user/:uid` : 사용자 삭제 (회원 탈퇴)
- [x] FaceImage
  - `GET` `/api/faces` : 전체 얼굴 이미지 조회
  - `GET` `/api/face/:uid` : 얼굴 단건 조회
  - `POST` `/api/face` : 얼굴 등록
  - `DELETE` `/api/face/:fid` : 얼굴 삭제
  - `DELETE` `/api/face/uid/:uid` : 얼굴 삭제 (추가)
- [x] Diary
  - `GET` `/api/diarys` : 일기 전체 목록 조회
  - `GET` `/api/diarys/:uid` : 내 일기 전체 목록 조회
  - `GET` `/api/diary/:did` : 일기 단건 조회
  - `POST` `/api/diary` : 일기 등록
  - `PUT` `/api/diary` : 일기 정보 수정
  - `DELETE` `/api/diary/:did` : 일기 삭제
- [x] Emotion
  - `GET` `/api/emotions` : 감정 분석 전체 목록 조회
  - `GET` `/api/emotion/:eid` : 감정 분석 단건 조회
  - `GET` `/api/emotions/uid/:uid` : 내 감정 분석 전체 목록 조회 (수정)
  - `GET` `/api/emotions/did/:did` : 내 감정 분석 전체 목록 조회 (추가)
  - `GET` `/api/emotion/date/${uid}?start=${start.toISOString()}&end=${end.toISOString()}` : 감정 분석 시작~끝 날짜로 조회 (추가)
  - `POST` `/api/emotion` : 감정 분석 등록
  - `PUT` (삭제)
  - `DELETE` `/api/emotion/:eid` : 감정 분석 삭제
  - `DELETE` `/api/emotion/did/:did` : 감정 분석 삭제 (추가)
  - `DELETE` `/api/emotion/uid/:uid` : 감정 분석 삭제 (추가)
- [x] Comment
  - `GET` `/api/comments` : 댓글 전체 목록 조회
  - `GET` `/api/comments/did/:did` : 해당 일기 댓글 전체 목록 조회
  - `POST` `/api/comment` : 댓글 등록
  - `PUT` `/api/comment` : 댓글 정보 수정
  - `DELETE` `/api/comment/:cid` : 댓글 삭제
- [x] Product
  - `GET` `/api/products` : 상품 전체 목록 조회
  - `GET` `/api/product/:pid` : 상품 단건 조회
  - `POST` `/api/product` : 상품 등록
  - `PUT` `/api/product` : 상품 정보 수정
  - `DELETE` `/api/product/:gid` : 상품 삭제
- [x] Cart
  - `GET` `/api/carts` : 카트 전체 목록 조회
  - `GET` `/api/carts/:uid` : 카트 전체 조회 - by 사용자 아이디
  - `GET` `/api/carts/:pid` : 카트 전체 조회 - by 상품
  - `POST` `/api/cart` : 카트 등록
  - `PUT` `/api/cart` : 카트 정보 수정
  - `DELETE` `/api/cart/:cid` : 카트 삭제
- [x] Bill
  - `GET` `/api/bills` : 영수증 전체 목록 조회
  - `GET` `/api/bill/:uid` : 영수증 단건 조회 - by 사용자 아이디
  - `POST` `/api/bill` : 영수증 등록
- [x] Like
  - `GET` `/api/likes` : 좋아요 전체 목록 조회
  - `GET` `/api/likes/:did` : 좋아요 전체 목록 조회 - by 일기 아이디
  - `GET` `/api/likes/:uid` : 좋아요 전체 목록 조회 - by 사용자 아이디
  - `POST` `/api/like` : 좋아요 등록
  - `DELETE` `/api/like/:lid` : 좋아요 삭제
  - `DELETE` `/api/like/did/:did` : 좋아요 삭제 (추가)
  - `DELETE` `/api/like/uid/:uid` : 좋아요 삭제 (추가)

**Comment by kkn1125** [comment]
- 각 모델 클래스의 필드 중 regdate와 updates는 모두 작성하는 것으로 방향 설정

**Comment by ohoraming** [comment]
- `Goods` 클래스를 `Product`로 `클래스명` 변경했음
   - `필드명`은 그대로 유지
- api 변경 사항 있음
  - [x] Product
    - `GET` `/api/products` : 상품 전체 목록 조회
    - `GET` `/api/product/:pid` : 상품 단건 조회
    - `POST` `/api/product` : 상품 등록
    - `PUT` `/api/product/:pid` : 상품 정보 수정
    - `DELETE` `/api/product/:pid` : 상품 삭제

**Comment by ohoraming** [comment]
- `Cart`는 `{cid}`로 CRUD 구현까지만 함
- 이후, `{uid}`와 `{pid}` 추가할 예정임

**Comment by kkn1125** [comment]
# API 추가 & 수정 현황

## User

  - `GET` `/api/user/nickname/:nickName` : 사용자 단건 조회 (추가)
  - `GET` `/api/user/email/:email` : 사용자 단건 조회 (추가)
  - `POST` `/api/face/signin` : 사용자 로그인 (안면인식 로그인) (추가)
  - `POST` `/api/signin` : 사용자 로그인 (일반 로그인) (추가)
  - `POST` `/token/confirm` : 토큰 확인 (추가)
  - `POST` `/user/signout` : 사용자 로그아웃 (추가)
  - `POST` `/user/checkPassword` : 비밀번호 확인 (추가)
  - `POST` `/fileupload` : 얼굴 이미지 업로드 (추가)

## FaceImage

  - `DELETE` `/api/face/uid/:uid` : 얼굴 삭제 (추가)

## Emotion

  - `GET` `/api/emotions/uid/:uid` : 내 감정분석 전체 목록 조회 (수정)
  - `GET` `/api/emotions/did/:did` : 내 감정분석 전체 목록 조회 (추가)
  - `PUT` (삭제)
  - `DELETE` `/api/emotion/did/:did` : 감정분석 삭제 (추가)
  - `DELETE` `/api/emotion/uid/:uid` : 감정분석 삭제 (추가)

## Like

  - `DELETE` `/api/like/did/:did` : 좋아요 삭제 (추가)
  - `DELETE` `/api/like/uid/:uid` : 좋아요 삭제 (추가)

**Comment by kkn1125** [comment]
`PUT` 요청 Endpoint 에 PathVariable 아이디값 받지 않는 것으로 수정!

---

이유는 아이디 값이 담긴 객체를 서버에서 받기 때문에 굳이 주소 엔드포인트에 주지 않고 객체를 받아 해당 객체의 id를 꺼내서 find하는 로직이기 때문에 수정함.

```javascript
// javascript api 부분

const formData = new FormData();
formData.append('id', product.id); // id를 객체에 담음
formData.append('...', ...);
// ...

axios.put('/api/product')
  .then((result) => {
    // ...
  })
  .catch((e) => {
    console.log(e.message);
  });
```

```java
// ProductRestController.java 부분
// ...

@PutMapping("/product")
public String update(Product product) {
  Product foundProduct = productRepository.findById(product.getId());
  foundProduct .replaceIfNotNull(product);
  return mapper(foundProduct);
}
```

**Comment by kkn1125** [comment]
Bill Class에 pid 필드가 아닌 cid(카트 아이디)를 들고와야 함. 수정 필요함. @ohoraming
