### ISSUE TITLE
[FE] 사이드바 및 profile 메뉴 수정 필요한 사항들

### ISSUE THREAD

**Issue by ohoraming** [kkn1125/narang#47]
- `Diary`메뉴 클릭시 나오는 사이드 바의 `공유일기`와 `사용법` 삭제 필요
    <img width="180" alt="image" src="https://user-images.githubusercontent.com/77590526/181718253-dc51888c-2417-496c-a000-2856131e554f.png">

- `Diary`메뉴 클릭시 나오는 `profile 메뉴`에 `logout` 추가 필요
    <img width="778" alt="image" src="https://user-images.githubusercontent.com/77590526/181721503-cf6fa96e-6f18-4b27-837d-eacb545c106e.png">

- `메인` 화면에 `Login` 버튼 필요(팝업창에서 sns login과 face login 선택)
    ![image](https://user-images.githubusercontent.com/77590526/181721038-6f8b560b-199f-4074-94b0-61a585cb80b8.png)

**Comment by kkn1125** [comment]
공유일기 -> 장바구니 (ohoraming 의견)
로그인 -> 프로필 드롭다운메뉴으로 이동
사용법 -> 보류
