### ISSUE TITLE
[FE] Cart page UI 작업

### ISSUE THREAD

**Issue by ohoraming** [kkn1125/narang#90]
> 예시1

![image](https://user-images.githubusercontent.com/77590526/183038876-23e339f7-92df-4e08-8c39-1c73dff5ebcb.png)

> 예시2

![image](https://user-images.githubusercontent.com/77590526/183039920-293cf2c2-981c-4066-bab1-a0c07d648698.png)

**Comment by ohoraming** [comment]
- 요소들을 세로로 배치하기로 함
   ![image](https://user-images.githubusercontent.com/77590526/183585654-759d6c27-1f9b-4139-98bd-20bd3a7b0209.png)

**Comment by kkn1125** [comment]
넘모 이쁨 😊
